/* =========================================================================
 * cues.js — Renkli ipucu öbekleri (cue phrases), 128 soru için elle küre edildi.
 *
 * İLKE (6 Tem 2026 — ürün kararı, Erkan):
 *  İpucu = sorunun KONU ÇAPASI: özel isim, tarih, sayı veya çekirdek
 *  kavram. Fiiller ve soru kalıpları renklenmez ("wrote the Declaration
 *  of Independence" değil "Declaration of Independence"; "happened on
 *  September 11" değil "on September 11"). Kullanıcı renkli çapayı
 *  duyduğunda konuyu tanır; hangi soru olduğunu çevredeki (renksiz)
 *  kelimeler belirler.
 *
 *  NOT: Eski sürümdeki "128 bankada benzersizlik" şartı bu kararla
 *  gevşetildi — aynı çapa birden çok soruda renklenebilir (örn.
 *  "Declaration of Independence" 8/78'de, "three branches" 15/16'da).
 *  Von Restorff vurgusu ve çift kodlama korunur; ayırt etme işi kısa
 *  çapayla değil cümlenin geri kalanıyla yapılır.
 *
 * KURAL (selfcheck.js doğrular): her ipucu, ait olduğu sorunun BİREBİR
 * alt dizisidir (kıvrık kesme işaretleri dahil) — vurgulama yerinde yapılır.
 * ========================================================================= */
"use strict";

const CUES = {
  1:   "form of government",
  2:   "supreme law",
  3:   "Constitution does",
  4:   "We the People",
  5:   "changes made",
  6:   "Bill of Rights",
  7:   "How many amendments",
  8:   "Declaration of Independence",
  9:   "free from Britain",
  10:  "two important ideas",
  11:  "pursuit of Happiness",
  12:  "economic system",
  13:  "rule of law",
  14:  "documents influenced",
  15:  "three branches",
  16:  "three branches",
  17:  "which branch",
  18:  "writes laws",
  19:  "two parts",
  20:  "power of the U.S. Congress",
  21:  "How many U.S. senators",
  22:  "term for a U.S. senator",
  23:  "your state’s U.S. senators",
  24:  "voting members",
  25:  "member of the House",
  26:  "shorter terms",
  27:  "How many senators",
  28:  "two senators",
  29:  "your U.S. representative",
  30:  "Speaker of the House",
  31:  "senator represent",
  32:  "Who elects U.S. senators",
  33:  "House of Representatives represent",
  34:  "elects members",
  35:  "more representatives",
  36:  "how many years",
  37:  "only two terms",
  38:  "name of the President",
  39:  "Vice President",
  40:  "no longer serve",
  41:  "power of the president",
  42:  "Commander in Chief",
  43:  "signs bills",
  44:  "vetoes",
  45:  "federal judges",
  46:  "executive branch",
  47:  "President’s Cabinet",
  48:  "Cabinet-level positions",
  49:  "Electoral College",
  50:  "judicial branch",
  51:  "judicial branch do",
  52:  "highest court",
  53:  "How many seats",
  54:  "decide a case",
  55:  "How long",
  56:  "for life",
  57:  "Chief Justice",
  58:  "only for the federal",
  59:  "only for the states",
  60:  "10th Amendment",
  61:  "governor",
  62:  "capital of your state",
  63:  "four amendments",
  64:  "serve on a jury",
  65:  "three rights",
  66:  "Pledge of Allegiance",
  67:  "two promises",
  68:  "become United States citizens",
  69:  "civic participation",
  70:  "serve their country",
  71:  "federal taxes",
  72:  "Selective Service",
  73:  "colonists came",
  74:  "before the Europeans",
  75:  "sold as slaves",
  76:  "win independence from Britain",
  77:  "declared independence",
  78:  "Declaration of Independence",
  79:  "adopted",
  80:  "American Revolution",
  81:  "13 original states",
  82:  "written in 1787",
  83:  "one of the writers",
  84:  "Federalist Papers",
  85:  "Benjamin Franklin",
  86:  "George Washington",
  87:  "Thomas Jefferson",
  88:  "James Madison",
  89:  "Alexander Hamilton",
  90:  "France in 1803",
  91:  "in the 1800s",
  92:  "North and the South",
  93:  "Civil War",
  94:  "Abraham Lincoln",
  95:  "Emancipation Proclamation",
  96:  "ended slavery",
  97:  "born or naturalized",
  98:  "all men",
  99:  "women’s rights movement",
  100: "1900s",
  101: "World War I",
  102: "all women",
  103: "Great Depression",
  104: "Great Depression start",
  105: "Great Depression and World War II",
  106: "enter World War II",
  107: "Dwight Eisenhower",
  108: "main rival",
  109: "main concern",
  110: "Korean War",
  111: "Vietnam War",
  112: "civil rights movement",
  113: "Martin Luther King",
  114: "Persian Gulf War",
  115: "on September 11",
  116: "military conflict after",
  117: "American Indian tribe",
  118: "American innovation",
  119: "capital of the United States",
  120: "Statue of Liberty",
  121: "13 stripes",
  122: "50 stars",
  123: "national anthem",
  124: "E Pluribus Unum",
  125: "Independence Day",
  126: "national U.S. holidays",
  127: "Memorial Day",
  128: "Veterans Day"
};
