/* =========================================================================
 * lang-es.js — İspanyolca dil katmanı (soru + ipucu + cevap çevirileri)
 *
 * lang-tr.js ile birebir aynı şablon:
 *   LANG_ES[id] = {
 *     q   : İspanyolca soru (cue'yu BİREBİR alt dize olarak içerir),
 *     cue : İspanyolca ipucu öbeği (cues.js'teki EN ipucunun anlam karşılığı),
 *     a   : İspanyolca cevaplar (data.js a dizisiyle AYNI SIRADA, paralel)
 *           veya null → cevaplar özel isim (Jefferson, eyaletler, kabileler)
 *           ya da ayarlardan gelir; İngilizce aynen gösterilir.
 *   }
 *
 * Terminoloji: USCIS'in resmî İspanyolca civics çeviri terminolojisi izlenir
 * (ör. "ley suprema de la nación", "Carta de Derechos" = Bill of Rights,
 *  "Colegio Electoral", "Corte Suprema", "enmiendas", "poder ejecutivo /
 *  legislativo / judicial", "Proclamación de Emancipación", "Guerra Civil").
 * ABD İspanyolcası (Latin Amerika), "usted" hitabı. Özel isimler çevrilmez.
 *
 * İngilizce içerik (data.js q/a) ASLA değişmez — sınav İngilizce.
 * Bu katman yalnızca anlam desteğidir (işleme derinliği: Craik & Lockhart).
 * ========================================================================= */
"use strict";

const LANG_ES = {
  1:   { q: "¿Cuál es la forma de gobierno de los Estados Unidos?",
         cue: "forma de gobierno",
         a: ["República", "República federal basada en una constitución", "Democracia representativa"] },
  2:   { q: "¿Cuál es la ley suprema de la nación?",
         cue: "ley suprema de la nación",
         a: ["La Constitución (de los EE. UU.)"] },
  3:   { q: "Mencione una cosa que hace la Constitución de los EE. UU.",
         cue: "que hace la Constitución",
         a: ["Establece el gobierno", "Define los poderes del gobierno", "Define las partes del gobierno", "Protege los derechos del pueblo"] },
  4:   { q: "La Constitución de los EE. UU. comienza con las palabras \"We the People\" (Nosotros el Pueblo). ¿Qué significa \"We the People\"?",
         cue: "We the People",
         a: ["Autogobierno", "Soberanía popular", "Consentimiento de los gobernados", "El pueblo debe gobernarse a sí mismo", "(Ejemplo de) contrato social"] },
  5:   { q: "¿Cómo se hacen los cambios a la Constitución de los EE. UU.?",
         cue: "se hacen los cambios",
         a: ["Con enmiendas", "Con el proceso de enmiendas"] },
  6:   { q: "¿Qué protege la Carta de Derechos (Bill of Rights)?",
         cue: "Bill of Rights",
         a: ["Los derechos (básicos) de los estadounidenses", "Los derechos (básicos) de las personas que viven en los Estados Unidos"] },
  7:   { q: "¿Cuántas enmiendas tiene la Constitución de los EE. UU.?",
         cue: "Cuántas enmiendas",
         a: ["Veintisiete (27)"] },
  8:   { q: "¿Por qué es importante la Declaración de Independencia?",
         cue: "Por qué es importante",
         a: ["Dice que los Estados Unidos es libre del control británico.", "Dice que todas las personas son creadas iguales.", "Identifica los derechos inherentes.", "Identifica las libertades individuales."] },
  9:   { q: "¿Qué documento fundacional dijo que las colonias americanas eran libres de Gran Bretaña?",
         cue: "libres de Gran Bretaña",
         a: ["La Declaración de Independencia"] },
  10:  { q: "Mencione dos ideas importantes de la Declaración de Independencia y de la Constitución de los EE. UU.",
         cue: "dos ideas importantes",
         a: ["Igualdad", "Libertad", "Contrato social", "Derechos naturales", "Gobierno limitado", "Autogobierno"] },
  11:  { q: "¿En qué documento fundacional se encuentran las palabras \"Vida, Libertad y la búsqueda de la Felicidad\"?",
         cue: "búsqueda de la Felicidad",
         a: ["La Declaración de Independencia"] },
  12:  { q: "¿Cuál es el sistema económico de los Estados Unidos?",
         cue: "sistema económico",
         a: ["Capitalismo", "Economía de libre mercado"] },
  13:  { q: "¿Qué es el estado de derecho?",
         cue: "estado de derecho",
         a: ["Todos deben obedecer la ley.", "Los líderes deben obedecer la ley.", "El gobierno debe obedecer la ley.", "Nadie está por encima de la ley."] },
  14:  { q: "Muchos documentos influyeron en la Constitución de los EE. UU. Mencione uno.",
         cue: "influyeron en la Constitución",
         a: ["La Declaración de Independencia", "Los Artículos de la Confederación", "Los Documentos Federalistas", "Los Documentos Antifederalistas", "La Declaración de Derechos de Virginia", "Las Órdenes Fundamentales de Connecticut", "El Pacto del Mayflower", "La Gran Ley de la Paz de los Iroqueses"] },
  15:  { q: "El gobierno tiene tres poderes. ¿Por qué?",
         cue: "tres poderes. ¿Por qué",
         a: ["Para que ninguna parte se vuelva demasiado poderosa", "Controles y equilibrios (checks and balances)", "Separación de poderes"] },
  16:  { q: "Mencione los tres poderes del gobierno.",
         cue: "Mencione los tres poderes",
         a: ["Legislativo, ejecutivo y judicial", "El Congreso, el presidente y los tribunales"] },
  17:  { q: "¿De qué poder del gobierno está a cargo el Presidente de los Estados Unidos?",
         cue: "está a cargo",
         a: ["El poder ejecutivo (executive branch)"] },
  18:  { q: "¿Qué parte del gobierno federal escribe las leyes?",
         cue: "escribe las leyes",
         a: ["El Congreso (de los EE. UU.)", "La legislatura (de los EE. UU. o nacional)", "El poder legislativo"] },
  19:  { q: "¿Cuáles son las dos partes del Congreso de los EE. UU.?",
         cue: "dos partes",
         a: ["El Senado y la Cámara (de Representantes)"] },
  20:  { q: "Mencione un poder del Congreso de los EE. UU.",
         cue: "un poder del Congreso",
         a: ["Escribe leyes", "Declara la guerra", "Elabora el presupuesto federal"] },
  21:  { q: "¿Cuántos senadores de los EE. UU. hay?",
         cue: "Cuántos senadores de los EE. UU.",
         a: ["Cien (100)"] },
  22:  { q: "¿Cuánto dura el término de un senador de los EE. UU.?",
         cue: "término de un senador",
         a: ["Seis (6) años"] },
  23:  { q: "¿Quién es ahora uno de los senadores de los EE. UU. de su estado?",
         cue: "senadores de los EE. UU. de su estado",
         a: null },
  24:  { q: "¿Cuántos miembros con derecho a voto hay en la Cámara de Representantes?",
         cue: "miembros con derecho a voto",
         a: ["Cuatrocientos treinta y cinco (435)"] },
  25:  { q: "¿Cuánto dura el término de un miembro de la Cámara de Representantes?",
         cue: "término de un miembro",
         a: ["Dos (2) años"] },
  26:  { q: "¿Por qué los representantes de los EE. UU. sirven términos más cortos que los senadores?",
         cue: "términos más cortos",
         a: ["Para seguir más de cerca la opinión pública"] },
  27:  { q: "¿Cuántos senadores tiene cada estado?",
         cue: "senadores tiene cada estado",
         a: ["Dos (2)"] },
  28:  { q: "¿Por qué cada estado tiene dos senadores?",
         cue: "dos senadores",
         a: ["Representación igualitaria (para los estados pequeños)", "El Gran Compromiso (Compromiso de Connecticut)"] },
  29:  { q: "Nombre a su representante de los EE. UU.",
         cue: "su representante",
         a: null },
  30:  { q: "¿Cómo se llama ahora el Presidente de la Cámara de Representantes (Speaker)?",
         cue: "Speaker",
         a: null },
  31:  { q: "¿A quién representa un senador de los EE. UU.?",
         cue: "quién representa un senador",
         a: ["A los ciudadanos de su estado", "Al pueblo de su estado"] },
  32:  { q: "¿Quién elige a los senadores de los EE. UU.?",
         cue: "elige a los senadores",
         a: ["Los ciudadanos de su estado"] },
  33:  { q: "¿A quién representa un miembro de la Cámara de Representantes?",
         cue: "quién representa un miembro",
         a: ["A los ciudadanos de su distrito (congresional)", "A los ciudadanos de su distrito", "Al pueblo de su distrito (congresional)", "Al pueblo de su distrito"] },
  34:  { q: "¿Quién elige a los miembros de la Cámara de Representantes?",
         cue: "elige a los miembros",
         a: ["Los ciudadanos de su distrito (congresional)"] },
  35:  { q: "Algunos estados tienen más representantes que otros. ¿Por qué?",
         cue: "más representantes",
         a: ["(Por) la población del estado", "(Porque) tienen más gente", "(Porque) algunos estados tienen más gente"] },
  36:  { q: "¿Por cuántos años se elige al Presidente de los Estados Unidos?",
         cue: "Por cuántos años se elige",
         a: ["Cuatro (4) años"] },
  37:  { q: "El Presidente de los Estados Unidos solo puede servir dos términos. ¿Por qué?",
         cue: "solo puede servir dos términos",
         a: ["(Por la) Enmienda 22", "Para evitar que el presidente se vuelva demasiado poderoso"] },
  38:  { q: "¿Cuál es el nombre del Presidente de los Estados Unidos ahora?",
         cue: "nombre del Presidente",
         a: null },
  39:  { q: "¿Cuál es el nombre del Vicepresidente de los Estados Unidos ahora?",
         cue: "Vicepresidente",
         a: null },
  40:  { q: "Si el presidente ya no puede servir, ¿quién se convierte en presidente?",
         cue: "ya no puede servir",
         a: ["El Vicepresidente (de los Estados Unidos)"] },
  41:  { q: "Mencione un poder del presidente.",
         cue: "un poder del presidente",
         a: ["Firma proyectos de ley para convertirlos en ley", "Veta proyectos de ley", "Hace cumplir las leyes", "Comandante en Jefe (de las fuerzas armadas)", "Jefe diplomático", "Nombra a los jueces federales"] },
  42:  { q: "¿Quién es el Comandante en Jefe de las fuerzas armadas de los EE. UU.?",
         cue: "Comandante en Jefe",
         a: ["El Presidente (de los Estados Unidos)"] },
  43:  { q: "¿Quién firma los proyectos de ley para que se conviertan en ley?",
         cue: "Quién firma",
         a: ["El Presidente (de los Estados Unidos)"] },
  44:  { q: "¿Quién veta los proyectos de ley?",
         cue: "veta",
         a: ["El Presidente (de los Estados Unidos)"] },
  45:  { q: "¿Quién nombra a los jueces federales?",
         cue: "nombra a los jueces",
         a: ["El Presidente (de los Estados Unidos)"] },
  46:  { q: "El poder ejecutivo tiene muchas partes. Mencione una.",
         cue: "El poder ejecutivo",
         a: ["El Presidente (de los Estados Unidos)", "El Gabinete", "Los departamentos y agencias federales"] },
  47:  { q: "¿Qué hace el Gabinete del Presidente?",
         cue: "Qué hace el Gabinete",
         a: ["Asesora al Presidente (de los Estados Unidos)"] },
  48:  { q: "¿Cuáles son dos puestos a nivel de gabinete?",
         cue: "puestos a nivel de gabinete",
         a: ["Procurador General (Attorney General)", "Secretario de Agricultura", "Secretario de Comercio", "Secretario de Educación", "Secretario de Energía", "Secretario de Salud y Servicios Humanos", "Secretario de Seguridad Nacional", "Secretario de Vivienda y Desarrollo Urbano", "Secretario del Interior", "Secretario del Trabajo", "Secretario de Estado (Secretary of State)", "Secretario de Transporte", "Secretario del Tesoro", "Secretario de Asuntos de Veteranos", "Secretario de Guerra (Defensa)", "Vicepresidente", "Administrador de la Agencia de Protección Ambiental (EPA)", "Director de la Agencia Central de Inteligencia (CIA)", "Director de la Oficina de Administración y Presupuesto", "Director de Inteligencia Nacional", "Representante Comercial de los Estados Unidos", "Administrador de la Administración de Pequeñas Empresas"] },
  49:  { q: "¿Por qué es importante el Colegio Electoral (Electoral College)?",
         cue: "Electoral College",
         a: ["Decide quién es elegido presidente.", "Ofrece un compromiso entre la elección popular del presidente y la selección por el Congreso."] },
  50:  { q: "¿Cuál es una parte del poder judicial?",
         cue: "una parte del poder judicial",
         a: ["La Corte Suprema (Supreme Court)", "Los tribunales federales"] },
  51:  { q: "¿Qué hace el poder judicial?",
         cue: "Qué hace el poder judicial",
         a: ["Revisa las leyes", "Explica las leyes", "Resuelve disputas (desacuerdos) sobre la ley", "Decide si una ley va en contra de la Constitución (de los EE. UU.)"] },
  52:  { q: "¿Cuál es el tribunal más alto de los Estados Unidos?",
         cue: "tribunal más alto",
         a: ["La Corte Suprema (Supreme Court)"] },
  53:  { q: "¿Cuántos asientos hay en la Corte Suprema?",
         cue: "Cuántos asientos",
         a: ["Nueve (9)"] },
  54:  { q: "¿Cuántos jueces de la Corte Suprema se necesitan usualmente para decidir un caso?",
         cue: "para decidir un caso",
         a: ["Cinco (5)"] },
  55:  { q: "¿Por cuánto tiempo sirven los jueces de la Corte Suprema?",
         cue: "Por cuánto tiempo",
         a: ["De por vida", "Nombramiento vitalicio", "(Hasta la) jubilación"] },
  56:  { q: "Los jueces de la Corte Suprema sirven de por vida. ¿Por qué?",
         cue: "de por vida. ¿Por qué",
         a: ["Para ser independientes (de la política)", "Para limitar la influencia (política) externa"] },
  57:  { q: "¿Quién es ahora el Presidente de la Corte Suprema (Chief Justice) de los Estados Unidos?",
         cue: "Chief Justice",
         a: null },
  58:  { q: "Mencione un poder que es solo del gobierno federal.",
         cue: "solo del gobierno federal",
         a: ["Imprimir papel moneda", "Acuñar monedas", "Declarar la guerra", "Crear un ejército", "Hacer tratados", "Establecer la política exterior"] },
  59:  { q: "Mencione un poder que es solo de los estados.",
         cue: "solo de los estados",
         a: ["Proveer escuelas y educación", "Proveer protección (policía)", "Proveer seguridad (cuerpos de bomberos)", "Otorgar licencias de conducir", "Aprobar la zonificación y el uso de la tierra"] },
  60:  { q: "¿Cuál es el propósito de la Enmienda 10?",
         cue: "Enmienda 10",
         a: ["(Establece que los) poderes no otorgados al gobierno federal pertenecen a los estados o al pueblo."] },
  61:  { q: "¿Quién es el gobernador de su estado ahora?",
         cue: "gobernador",
         a: null },
  62:  { q: "¿Cuál es la capital de su estado?",
         cue: "capital de su estado",
         a: null },
  63:  { q: "Hay cuatro enmiendas a la Constitución de los EE. UU. sobre quién puede votar. Describa una de ellas.",
         cue: "cuatro enmiendas",
         a: ["Los ciudadanos de dieciocho (18) años o más (pueden votar).", "No hay que pagar (un impuesto electoral) para votar.", "Cualquier ciudadano puede votar. (Tanto las mujeres como los hombres pueden votar.)", "Un ciudadano varón de cualquier raza (puede votar)."] },
  64:  { q: "¿Quién puede votar en las elecciones federales, postularse para un cargo federal y servir en un jurado en los Estados Unidos?",
         cue: "servir en un jurado",
         a: ["Los ciudadanos", "Los ciudadanos de los Estados Unidos", "Los ciudadanos estadounidenses"] },
  65:  { q: "¿Cuáles son tres derechos de todas las personas que viven en los Estados Unidos?",
         cue: "tres derechos",
         a: ["Libertad de expresión", "Libertad de palabra", "Libertad de reunión", "Libertad de peticionar al gobierno", "Libertad de religión", "El derecho a portar armas"] },
  66:  { q: "¿A qué le mostramos lealtad cuando decimos el Juramento de Lealtad (Pledge of Allegiance)?",
         cue: "Pledge of Allegiance",
         a: ["A los Estados Unidos", "A la bandera"] },
  67:  { q: "Mencione dos promesas que los nuevos ciudadanos hacen en el Juramento de Lealtad (Oath of Allegiance).",
         cue: "dos promesas",
         a: ["Renunciar a la lealtad a otros países", "Defender la Constitución (de los EE. UU.)", "Obedecer las leyes de los Estados Unidos", "Servir en las fuerzas armadas (si fuera necesario)", "Servir a (ayudar a, hacer trabajo importante para) la nación (si fuera necesario)", "Ser leal a los Estados Unidos"] },
  68:  { q: "¿Cómo pueden las personas convertirse en ciudadanos de los Estados Unidos?",
         cue: "convertirse en ciudadanos",
         a: ["Nacer en los Estados Unidos, bajo las condiciones establecidas por la Enmienda 14", "Naturalizarse", "Derivar la ciudadanía (bajo las condiciones establecidas por el Congreso)"] },
  69:  { q: "¿Cuáles son dos ejemplos de participación cívica en los Estados Unidos?",
         cue: "participación cívica",
         a: ["Votar", "Postularse para un cargo", "Afiliarse a un partido político", "Ayudar en una campaña", "Unirse a un grupo cívico", "Unirse a un grupo comunitario", "Dar su opinión a un funcionario electo (sobre un asunto)", "Comunicarse con los funcionarios electos", "Apoyar u oponerse a un asunto o política", "Escribir a un periódico"] },
  70:  { q: "¿Cuál es una manera en que los estadounidenses pueden servir a su país?",
         cue: "servir a su país",
         a: ["Votar", "Pagar impuestos", "Obedecer la ley", "Servir en las fuerzas armadas", "Postularse para un cargo", "Trabajar para el gobierno local, estatal o federal"] },
  71:  { q: "¿Por qué es importante pagar los impuestos federales?",
         cue: "pagar los impuestos",
         a: ["Lo exige la ley", "Todas las personas pagan para financiar al gobierno federal", "Lo exige la Constitución (de los EE. UU.) (Enmienda 16)", "Es un deber cívico"] },
  72:  { q: "Es importante que todos los hombres de 18 a 25 años se inscriban en el Servicio Selectivo (Selective Service). Mencione una razón.",
         cue: "Selective Service",
         a: ["Lo exige la ley", "Es un deber cívico", "Hace que el reclutamiento sea justo, si fuera necesario"] },
  73:  { q: "Los colonos vinieron a América por muchas razones. Mencione una.",
         cue: "Los colonos",
         a: ["Libertad", "Libertad política", "Libertad religiosa", "Oportunidad económica", "Escapar de la persecución"] },
  74:  { q: "¿Quiénes vivían en América antes de la llegada de los europeos?",
         cue: "antes de la llegada de los europeos",
         a: ["Los indios americanos", "Los nativos americanos (Native Americans)"] },
  75:  { q: "¿Qué grupo de personas fue tomado y vendido como esclavos?",
         cue: "vendido como esclavos",
         a: ["Los africanos", "Personas de África"] },
  76:  { q: "¿Qué guerra pelearon los estadounidenses para ganar la independencia de Gran Bretaña?",
         cue: "ganar la independencia",
         a: ["La Revolución Americana", "La Guerra Revolucionaria (Americana)", "La Guerra de Independencia (de los EE. UU.)"] },
  77:  { q: "Mencione una razón por la que los estadounidenses declararon la independencia de Gran Bretaña.",
         cue: "declararon la independencia",
         a: ["Impuestos altos", "Impuestos sin representación", "Los soldados británicos se quedaban en las casas de los estadounidenses (alojamiento, acuartelamiento)", "No tenían autogobierno", "La Masacre de Boston", "El Motín del Té de Boston (Ley del Té)", "La Ley del Sello (Stamp Act)", "La Ley del Azúcar", "Las Leyes de Townshend", "Las Leyes Intolerables (Coercitivas)"] },
  78:  { q: "¿Quién escribió la Declaración de Independencia?",
         cue: "Quién escribió",
         a: null },
  79:  { q: "¿Cuándo fue adoptada la Declaración de Independencia?",
         cue: "Cuándo fue adoptada",
         a: ["El 4 de julio de 1776"] },
  80:  { q: "La Revolución Americana tuvo muchos eventos importantes. Mencione uno.",
         cue: "La Revolución Americana",
         a: ["(La Batalla de) Bunker Hill", "La Declaración de Independencia", "El cruce del río Delaware por Washington (Batalla de Trenton)", "(La Batalla de) Saratoga", "(El campamento de) Valley Forge", "(La Batalla de) Yorktown (la rendición británica en Yorktown)"] },
  81:  { q: "Había 13 estados originales. Mencione cinco.",
         cue: "13 estados originales",
         a: null },
  82:  { q: "¿Qué documento fundacional fue escrito en 1787?",
         cue: "1787",
         a: ["La Constitución (de los EE. UU.)"] },
  83:  { q: "Los Documentos Federalistas apoyaron la aprobación de la Constitución de los EE. UU. Mencione a uno de los escritores.",
         cue: "uno de los escritores",
         a: null },
  84:  { q: "¿Por qué fueron importantes los Documentos Federalistas?",
         cue: "Por qué fueron importantes",
         a: ["Ayudaron a la gente a entender la Constitución (de los EE. UU.).", "Apoyaron la aprobación de la Constitución (de los EE. UU.)."] },
  85:  { q: "Benjamin Franklin es famoso por muchas cosas. Mencione una.",
         cue: "Benjamin Franklin",
         a: ["Fundó las primeras bibliotecas públicas gratuitas", "Primer Director General de Correos de los Estados Unidos", "Ayudó a escribir la Declaración de Independencia", "Inventor", "Diplomático de los EE. UU."] },
  86:  { q: "George Washington es famoso por muchas cosas. Mencione una.",
         cue: "George Washington",
         a: ["\"Padre de Nuestra Nación\"", "Primer presidente de los Estados Unidos", "General del Ejército Continental", "Presidente de la Convención Constitucional"] },
  87:  { q: "Thomas Jefferson es famoso por muchas cosas. Mencione una.",
         cue: "Thomas Jefferson",
         a: ["Escritor de la Declaración de Independencia", "Tercer presidente de los Estados Unidos", "Duplicó el tamaño de los Estados Unidos (Compra de Louisiana)", "Primer Secretario de Estado", "Fundó la Universidad de Virginia", "Escritor del Estatuto de Virginia sobre la Libertad Religiosa"] },
  88:  { q: "James Madison es famoso por muchas cosas. Mencione una.",
         cue: "James Madison",
         a: ["\"Padre de la Constitución\"", "Cuarto presidente de los Estados Unidos", "Presidente durante la Guerra de 1812", "Uno de los escritores de los Documentos Federalistas"] },
  89:  { q: "Alexander Hamilton es famoso por muchas cosas. Mencione una.",
         cue: "Alexander Hamilton",
         a: ["Primer Secretario del Tesoro", "Uno de los escritores de los Documentos Federalistas", "Ayudó a establecer el Primer Banco de los Estados Unidos", "Ayudante del General George Washington", "Miembro del Congreso Continental"] },
  90:  { q: "¿Qué territorio compró los Estados Unidos a Francia en 1803?",
         cue: "a Francia",
         a: ["El Territorio de Louisiana", "Louisiana"] },
  91:  { q: "Mencione una guerra peleada por los Estados Unidos en los años 1800.",
         cue: "los años 1800",
         a: ["La Guerra de 1812", "La Guerra entre México y los Estados Unidos", "La Guerra Civil", "La Guerra Hispano-Estadounidense"] },
  92:  { q: "Mencione la guerra de los EE. UU. entre el Norte y el Sur.",
         cue: "el Norte y el Sur",
         a: ["La Guerra Civil (Civil War)"] },
  93:  { q: "La Guerra Civil tuvo muchos eventos importantes. Mencione uno.",
         cue: "La Guerra Civil tuvo",
         a: ["(La Batalla de) Fort Sumter", "La Proclamación de Emancipación", "(La Batalla de) Vicksburg", "(La Batalla de) Gettysburg", "La Marcha de Sherman", "(La rendición en) Appomattox", "(La Batalla de) Antietam/Sharpsburg", "Lincoln fue asesinado."] },
  94:  { q: "Abraham Lincoln es famoso por muchas cosas. Mencione una.",
         cue: "Abraham Lincoln",
         a: ["Liberó a los esclavos (Proclamación de Emancipación)", "Salvó (o preservó) la Unión", "Dirigió a los Estados Unidos durante la Guerra Civil", "Decimosexto (16.º) presidente de los Estados Unidos", "Pronunció el Discurso de Gettysburg"] },
  95:  { q: "¿Qué hizo la Proclamación de Emancipación?",
         cue: "Proclamación de Emancipación",
         a: ["Liberó a los esclavos", "Liberó a los esclavos de la Confederación", "Liberó a los esclavos en los estados confederados", "Liberó a los esclavos en la mayoría de los estados del Sur"] },
  96:  { q: "¿Qué guerra de los EE. UU. puso fin a la esclavitud?",
         cue: "puso fin a la esclavitud",
         a: ["La Guerra Civil (Civil War)"] },
  97:  { q: "¿Qué enmienda dice que todas las personas nacidas o naturalizadas en los Estados Unidos, y sujetas a su jurisdicción, son ciudadanos de los EE. UU.?",
         cue: "nacidas o naturalizadas",
         a: ["La Enmienda 14"] },
  98:  { q: "¿Cuándo obtuvieron todos los hombres el derecho al voto?",
         cue: "los hombres el derecho al voto",
         a: ["Después de la Guerra Civil", "Durante la Reconstrucción", "(Con la) Enmienda 15", "1870"] },
  99:  { q: "Mencione a una líder del movimiento por los derechos de la mujer en los años 1800.",
         cue: "derechos de la mujer",
         a: null },
  100: { q: "Mencione una guerra peleada por los Estados Unidos en los años 1900.",
         cue: "los años 1900",
         a: ["La Primera Guerra Mundial", "La Segunda Guerra Mundial", "La Guerra de Corea", "La Guerra de Vietnam", "La Guerra del Golfo (Pérsico)"] },
  101: { q: "¿Por qué entró los Estados Unidos en la Primera Guerra Mundial?",
         cue: "Primera Guerra Mundial",
         a: ["Porque Alemania atacó barcos (civiles) estadounidenses", "Para apoyar a las Potencias Aliadas (Inglaterra, Francia, Italia y Rusia)", "Para oponerse a las Potencias Centrales (Alemania, Austria-Hungría, el Imperio Otomano y Bulgaria)"] },
  102: { q: "¿Cuándo obtuvieron todas las mujeres el derecho al voto?",
         cue: "las mujeres el derecho al voto",
         a: ["1920", "Después de la Primera Guerra Mundial", "(Con la) Enmienda 19"] },
  103: { q: "¿Qué fue la Gran Depresión?",
         cue: "Qué fue la Gran Depresión",
         a: ["La recesión económica más larga de la historia moderna"] },
  104: { q: "¿Cuándo comenzó la Gran Depresión?",
         cue: "Cuándo comenzó",
         a: ["La Gran Caída (1929)", "El colapso de la bolsa de valores de 1929"] },
  105: { q: "¿Quién era presidente durante la Gran Depresión y la Segunda Guerra Mundial?",
         cue: "Depresión y la Segunda Guerra Mundial",
         a: ["(Franklin) Roosevelt"] },
  106: { q: "¿Por qué entró los Estados Unidos en la Segunda Guerra Mundial?",
         cue: "entró los Estados Unidos en la Segunda Guerra Mundial",
         a: ["(El bombardeo de) Pearl Harbor", "Los japoneses atacaron Pearl Harbor", "Para apoyar a las Potencias Aliadas (Inglaterra, Francia y Rusia)", "Para oponerse a las Potencias del Eje (Alemania, Italia y Japón)"] },
  107: { q: "Dwight Eisenhower es famoso por muchas cosas. Mencione una.",
         cue: "Dwight Eisenhower",
         a: ["General durante la Segunda Guerra Mundial", "Presidente al final de (durante) la Guerra de Corea", "Trigésimo cuarto (34.º) presidente de los Estados Unidos", "Firmó la Ley Federal de Ayuda para Carreteras de 1956 (creó el Sistema Interestatal de Carreteras)"] },
  108: { q: "Durante la Guerra Fría, ¿cuál fue el principal rival de los Estados Unidos?",
         cue: "principal rival",
         a: ["La Unión Soviética", "La URSS", "Rusia"] },
  109: { q: "Durante la Guerra Fría, ¿cuál fue una preocupación principal de los Estados Unidos?",
         cue: "preocupación principal",
         a: ["El comunismo", "La guerra nuclear"] },
  110: { q: "¿Por qué entró los Estados Unidos en la Guerra de Corea?",
         cue: "Guerra de Corea",
         a: ["Para detener la propagación del comunismo"] },
  111: { q: "¿Por qué entró los Estados Unidos en la Guerra de Vietnam?",
         cue: "Guerra de Vietnam",
         a: ["Para detener la propagación del comunismo"] },
  112: { q: "¿Qué hizo el movimiento por los derechos civiles?",
         cue: "derechos civiles",
         a: ["Luchó para poner fin a la discriminación racial"] },
  113: { q: "Martin Luther King, Jr. es famoso por muchas cosas. Mencione una.",
         cue: "Martin Luther King",
         a: ["Luchó por los derechos civiles", "Trabajó por la igualdad de todos los estadounidenses", "Trabajó para asegurar que las personas \"no fueran juzgadas por el color de su piel, sino por el contenido de su carácter\""] },
  114: { q: "¿Por qué entró los Estados Unidos en la Guerra del Golfo Pérsico?",
         cue: "Golfo Pérsico",
         a: ["Para expulsar al ejército iraquí de Kuwait"] },
  115: { q: "¿Qué evento importante ocurrió el 11 de septiembre de 2001 en los Estados Unidos?",
         cue: "11 de septiembre de 2001",
         a: ["Los terroristas atacaron los Estados Unidos", "Los terroristas se apoderaron de dos aviones y los estrellaron contra el World Trade Center en la ciudad de Nueva York", "Los terroristas se apoderaron de un avión y lo estrellaron contra el Pentágono en Arlington, Virginia", "Los terroristas se apoderaron de un avión dirigido originalmente a Washington, D.C., que se estrelló en un campo de Pensilvania"] },
  116: { q: "Mencione un conflicto militar de los EE. UU. después de los ataques del 11 de septiembre de 2001.",
         cue: "después de los ataques",
         a: ["La Guerra (Global) contra el Terrorismo", "La Guerra en Afganistán", "La Guerra en Irak"] },
  117: { q: "Mencione una tribu de indios americanos de los Estados Unidos.",
         cue: "tribu de indios americanos",
         a: null },
  118: { q: "Mencione un ejemplo de una innovación estadounidense.",
         cue: "innovación estadounidense",
         a: ["La bombilla eléctrica (el foco)", "El automóvil (los carros, el motor de combustión interna)", "Los rascacielos", "El avión", "La línea de ensamblaje", "El alunizaje (la llegada a la Luna)", "El circuito integrado (IC)"] },
  119: { q: "¿Cuál es la capital de los Estados Unidos?",
         cue: "capital de los Estados Unidos",
         a: ["Washington, D.C."] },
  120: { q: "¿Dónde está la Estatua de la Libertad?",
         cue: "Estatua de la Libertad",
         a: ["(El puerto de) Nueva York", "La Isla de la Libertad (Liberty Island)"] },
  121: { q: "¿Por qué tiene la bandera 13 franjas?",
         cue: "13 franjas",
         a: ["(Porque había) 13 colonias originales", "(Porque las franjas) representan las colonias originales"] },
  122: { q: "¿Por qué tiene la bandera 50 estrellas?",
         cue: "50 estrellas",
         a: ["(Porque hay) una estrella por cada estado", "(Porque) cada estrella representa un estado", "(Porque hay) 50 estados"] },
  123: { q: "¿Cómo se llama el himno nacional?",
         cue: "himno nacional",
         a: null },
  124: { q: "El primer lema de la Nación fue \"E Pluribus Unum\". ¿Qué significa?",
         cue: "E Pluribus Unum",
         a: ["De muchos, uno", "Todos nos convertimos en uno"] },
  125: { q: "¿Qué es el Independence Day (Día de la Independencia)?",
         cue: "Independence Day",
         a: ["Un día festivo para celebrar la independencia de los EE. UU. (de Gran Bretaña)", "El cumpleaños del país"] },
  126: { q: "Mencione tres días festivos nacionales de los EE. UU.",
         cue: "tres días festivos nacionales",
         a: ["El Día de Año Nuevo", "El Día de Martin Luther King, Jr.", "El Día de los Presidentes (Cumpleaños de Washington)", "El Memorial Day (Día de la Recordación)", "Juneteenth (Día de la Emancipación)", "El Día de la Independencia", "El Día del Trabajo (Labor Day)", "El Día de Cristóbal Colón (Columbus Day)", "El Veterans Day (Día de los Veteranos)", "El Día de Acción de Gracias (Thanksgiving)", "El Día de Navidad"] },
  127: { q: "¿Qué es el Memorial Day (Día de la Recordación)?",
         cue: "Memorial Day",
         a: ["Un día festivo para honrar a los soldados que murieron en el servicio militar"] },
  128: { q: "¿Qué es el Veterans Day (Día de los Veteranos)?",
         cue: "Veterans Day",
         a: ["Un día festivo para honrar a las personas de las fuerzas armadas (de los EE. UU.)", "Un día festivo para honrar a las personas que han servido (en las fuerzas armadas de los EE. UU.)"] }
};
