/* =========================================================================
 * lang-tr.js — Türkçe dil katmanı (soru + ipucu + cevap çevirileri)
 *
 * Yapı (gelecekteki lang-es.js aynı şablonu kullanır):
 *   LANG_TR[id] = {
 *     q   : Türkçe soru (cue'yu BİREBİR alt dize olarak içerir),
 *     cue : Türkçe ipucu öbeği (cues.js'teki EN ipucunun anlam karşılığı),
 *     a   : Türkçe cevaplar (data.js a dizisiyle AYNI SIRADA, paralel)
 *           veya null → cevaplar özel isim (Jefferson, eyaletler, kabileler)
 *           ya da ayarlardan gelir; İngilizce aynen gösterilir.
 *   }
 *
 * İngilizce içerik (data.js q/a) ASLA değişmez — sınav İngilizce.
 * Bu katman yalnızca anlam desteğidir (işleme derinliği: Craik & Lockhart).
 * ========================================================================= */
"use strict";

const LANG_TR = {
  1:   { q: "Amerika Birleşik Devletleri'nin yönetim biçimi nedir?",
         cue: "yönetim biçimi",
         a: ["Cumhuriyet", "Anayasaya dayalı federal cumhuriyet", "Temsilî demokrasi"] },
  2:   { q: "Ülkenin en üstün yasası nedir?",
         cue: "en üstün yasası",
         a: ["(ABD) Anayasası"] },
  3:   { q: "ABD Anayasası'nın yaptığı bir şeyi söyleyin.",
         cue: "Anayasası'nın yaptığı",
         a: ["Hükümeti kurar", "Hükümetin yetkilerini tanımlar", "Hükümetin bölümlerini tanımlar", "Halkın haklarını korur"] },
  4:   { q: "ABD Anayasası \"We the People\" (Biz Halk) sözleriyle başlar. \"We the People\" ne anlama gelir?",
         cue: "We the People",
         a: ["Öz yönetim", "Halk egemenliği", "Yönetilenlerin rızası", "Halk kendi kendini yönetmelidir", "(Toplumsal sözleşme örneği)"] },
  5:   { q: "ABD Anayasası'nda değişiklikler nasıl yapılır?",
         cue: "değişiklikler nasıl yapılır",
         a: ["Anayasa değişiklikleriyle (amendment)", "Değişiklik süreciyle"] },
  6:   { q: "Haklar Bildirgesi (Bill of Rights) neyi korur?",
         cue: "Bill of Rights",
         a: ["Amerikalıların (temel) haklarını", "ABD'de yaşayan insanların (temel) haklarını"] },
  7:   { q: "ABD Anayasası'nda kaç değişiklik vardır?",
         cue: "kaç değişiklik",
         a: ["Yirmi yedi (27)"] },
  8:   { q: "Bağımsızlık Bildirgesi neden önemlidir?",
         cue: "Bağımsızlık Bildirgesi",
         a: ["Amerika'nın İngiliz kontrolünden özgür olduğunu söyler.", "Tüm insanların eşit yaratıldığını söyler.", "Doğuştan gelen hakları tanımlar.", "Bireysel özgürlükleri tanımlar."] },
  9:   { q: "Hangi kurucu belge Amerikan kolonilerinin İngiltere'den özgür olduğunu söyledi?",
         cue: "İngiltere'den özgür",
         a: ["Bağımsızlık Bildirgesi"] },
  10:  { q: "Bağımsızlık Bildirgesi ve ABD Anayasası'ndan iki önemli fikir söyleyin.",
         cue: "iki önemli fikir",
         a: ["Eşitlik", "Özgürlük", "Toplumsal sözleşme", "Doğal haklar", "Sınırlı hükümet", "Öz yönetim"] },
  11:  { q: "\"Yaşam, Özgürlük ve Mutluluğu Arama\" sözleri hangi kurucu belgede yer alır?",
         cue: "Mutluluğu Arama",
         a: ["Bağımsızlık Bildirgesi"] },
  12:  { q: "Amerika Birleşik Devletleri'nin ekonomik sistemi nedir?",
         cue: "ekonomik sistemi",
         a: ["Kapitalizm", "Serbest piyasa ekonomisi"] },
  13:  { q: "Hukukun üstünlüğü nedir?",
         cue: "Hukukun üstünlüğü",
         a: ["Herkes yasalara uymak zorundadır.", "Liderler yasalara uymak zorundadır.", "Hükümet yasalara uymak zorundadır.", "Kimse yasaların üstünde değildir."] },
  14:  { q: "Birçok belge ABD Anayasası'nı etkiledi. Birini söyleyin.",
         cue: "Anayasası'nı etkiledi",
         a: ["Bağımsızlık Bildirgesi", "Konfederasyon Maddeleri", "Federalist Yazıları", "Anti-Federalist Yazıları", "Virginia Haklar Bildirgesi", "Connecticut Temel Düzenleri", "Mayflower Sözleşmesi", "İrokua Büyük Barış Yasası"] },
  15:  { q: "Hükümetin üç erki vardır. Neden?",
         cue: "üç erki",
         a: ["Bir bölüm aşırı güçlenmesin diye", "Denge ve denetim (checks and balances)", "Güçler ayrılığı"] },
  16:  { q: "Hükümetin üç erkini sayın.",
         cue: "üç erkini",
         a: ["Yasama, yürütme ve yargı", "Kongre, başkan ve mahkemeler"] },
  17:  { q: "ABD Başkanı hangi erkin başındadır?",
         cue: "hangi erkin",
         a: ["Yürütme erki (executive branch)"] },
  18:  { q: "Federal hükümetin hangi bölümü yasaları yazar?",
         cue: "yasaları yazar",
         a: ["(ABD) Kongresi", "(ABD veya ulusal) yasama organı", "Yasama erki"] },
  19:  { q: "ABD Kongresi'nin iki kanadı nedir?",
         cue: "iki kanadı",
         a: ["Senato ve Temsilciler Meclisi"] },
  20:  { q: "ABD Kongresi'nin bir yetkisini söyleyin.",
         cue: "Kongresi'nin bir yetkisini",
         a: ["Yasa yazar", "Savaş ilan eder", "Federal bütçeyi yapar"] },
  21:  { q: "Kaç ABD senatörü vardır?",
         cue: "Kaç ABD senatörü",
         a: ["Yüz (100)"] },
  22:  { q: "Bir ABD senatörünün görev süresi kaç yıldır?",
         cue: "senatörünün görev süresi",
         a: ["Altı (6) yıl"] },
  23:  { q: "Şu anda eyaletinizin ABD senatörlerinden biri kimdir?",
         cue: "eyaletinizin ABD senatörlerinden",
         a: null },
  24:  { q: "Temsilciler Meclisi'nde kaç oy hakkına sahip üye vardır?",
         cue: "oy hakkına sahip üye",
         a: ["Dört yüz otuz beş (435)"] },
  25:  { q: "Temsilciler Meclisi üyesinin görev süresi kaç yıldır?",
         cue: "üyesinin görev süresi",
         a: ["İki (2) yıl"] },
  26:  { q: "ABD temsilcileri neden senatörlerden daha kısa süre görev yapar?",
         cue: "daha kısa süre",
         a: ["Kamuoyunu daha yakından izlemek için"] },
  27:  { q: "Her eyaletin kaç senatörü vardır?",
         cue: "kaç senatörü",
         a: ["İki (2)"] },
  28:  { q: "Neden her eyaletin iki senatörü vardır?",
         cue: "iki senatörü",
         a: ["(Küçük eyaletler için) eşit temsil", "Büyük Uzlaşma (Connecticut Uzlaşması)"] },
  29:  { q: "ABD temsilcinizin adını söyleyin.",
         cue: "temsilcinizin",
         a: null },
  30:  { q: "Şu anda Temsilciler Meclisi Başkanı'nın (Speaker) adı nedir?",
         cue: "Speaker",
         a: null },
  31:  { q: "Bir ABD senatörü kimi temsil eder?",
         cue: "senatörü kimi temsil",
         a: ["Eyaletinin vatandaşlarını", "Eyaletinin halkını"] },
  32:  { q: "ABD senatörlerini kim seçer?",
         cue: "senatörlerini kim seçer",
         a: ["Eyaletlerinin vatandaşları"] },
  33:  { q: "Temsilciler Meclisi üyesi kimi temsil eder?",
         cue: "üyesi kimi temsil",
         a: ["(Kongre) bölgesindeki vatandaşları", "Bölgesindeki vatandaşları", "(Kongre) bölgesinin halkını", "Bölgesinin halkını"] },
  34:  { q: "Temsilciler Meclisi üyelerini kim seçer?",
         cue: "üyelerini kim seçer",
         a: ["(Kongre) bölgelerinin vatandaşları"] },
  35:  { q: "Bazı eyaletlerin diğerlerinden daha fazla temsilcisi vardır. Neden?",
         cue: "daha fazla temsilcisi",
         a: ["Eyaletin nüfusu (nedeniyle)", "Daha çok insanları olduğu (için)", "Bazı eyaletlerde daha çok insan yaşadığı (için)"] },
  36:  { q: "ABD Başkanı kaç yıllığına seçilir?",
         cue: "kaç yıllığına",
         a: ["Dört (4) yıl"] },
  37:  { q: "ABD Başkanı yalnızca iki dönem görev yapabilir. Neden?",
         cue: "yalnızca iki dönem",
         a: ["22. Anayasa Değişikliği (nedeniyle)", "Başkanın aşırı güçlenmesini önlemek için"] },
  38:  { q: "Şu anda ABD Başkanı'nın adı nedir?",
         cue: "Başkanı'nın adı",
         a: null },
  39:  { q: "Şu anda ABD Başkan Yardımcısı'nın adı nedir?",
         cue: "Başkan Yardımcısı",
         a: null },
  40:  { q: "Başkan artık görev yapamazsa, kim başkan olur?",
         cue: "artık görev yapamazsa",
         a: ["(ABD) Başkan Yardımcısı"] },
  41:  { q: "Başkanın bir yetkisini söyleyin.",
         cue: "Başkanın bir yetkisini",
         a: ["Tasarıları imzalayıp yasalaştırır", "Tasarıları veto eder", "Yasaları uygular", "(Ordunun) Başkomutanı", "Baş diplomat", "Federal yargıçları atar"] },
  42:  { q: "ABD ordusunun Başkomutanı kimdir?",
         cue: "Başkomutanı",
         a: ["(ABD) Başkanı"] },
  43:  { q: "Tasarıları yasalaşmaları için kim imzalar?",
         cue: "kim imzalar",
         a: ["(ABD) Başkanı"] },
  44:  { q: "Tasarıları kim veto eder?",
         cue: "veto",
         a: ["(ABD) Başkanı"] },
  45:  { q: "Federal yargıçları kim atar?",
         cue: "Federal yargıçları",
         a: ["(ABD) Başkanı"] },
  46:  { q: "Yürütme erkinin birçok bölümü vardır. Birini söyleyin.",
         cue: "Yürütme erkinin",
         a: ["(ABD) Başkanı", "Kabine", "Federal bakanlıklar ve kurumlar"] },
  47:  { q: "Başkanın Kabinesi ne yapar?",
         cue: "Kabinesi ne yapar",
         a: ["(ABD) Başkanına danışmanlık yapar"] },
  48:  { q: "İki Kabine düzeyinde pozisyon söyleyin.",
         cue: "Kabine düzeyinde pozisyon",
         a: ["Adalet Bakanı (Attorney General)", "Tarım Bakanı", "Ticaret Bakanı", "Eğitim Bakanı", "Enerji Bakanı", "Sağlık ve Sosyal Hizmetler Bakanı", "İç Güvenlik Bakanı", "Konut ve Kentsel Gelişim Bakanı", "İçişleri Bakanı", "Çalışma Bakanı", "Dışişleri Bakanı (Secretary of State)", "Ulaştırma Bakanı", "Hazine Bakanı", "Gaziler Bakanı", "Savaş (Savunma) Bakanı", "Başkan Yardımcısı", "Çevre Koruma Ajansı (EPA) Yöneticisi", "Merkezi İstihbarat Teşkilatı (CIA) Direktörü", "Yönetim ve Bütçe Ofisi Direktörü", "Ulusal İstihbarat Direktörü", "ABD Ticaret Temsilcisi", "Küçük İşletmeler İdaresi Yöneticisi"] },
  49:  { q: "Seçiciler Kurulu (Electoral College) neden önemlidir?",
         cue: "Electoral College",
         a: ["Başkanın kim seçileceğine karar verir.", "Başkanın halk tarafından seçilmesi ile Kongre tarafından seçilmesi arasında bir uzlaşma sağlar."] },
  50:  { q: "Yargı erkinin bir bölümünü söyleyin.",
         cue: "Yargı erkinin",
         a: ["Yüksek Mahkeme (Supreme Court)", "Federal mahkemeler"] },
  51:  { q: "Yargı erki ne yapar?",
         cue: "Yargı erki ne yapar",
         a: ["Yasaları inceler", "Yasaları açıklar", "Yasayla ilgili uyuşmazlıkları (anlaşmazlıkları) çözer", "Bir yasanın (ABD) Anayasası'na aykırı olup olmadığına karar verir"] },
  52:  { q: "Amerika Birleşik Devletleri'ndeki en yüksek mahkeme hangisidir?",
         cue: "en yüksek mahkeme",
         a: ["Yüksek Mahkeme (Supreme Court)"] },
  53:  { q: "Yüksek Mahkeme'de kaç koltuk vardır?",
         cue: "kaç koltuk",
         a: ["Dokuz (9)"] },
  54:  { q: "Bir davayı karara bağlamak için genellikle kaç Yüksek Mahkeme yargıcı gerekir?",
         cue: "davayı karara bağlamak",
         a: ["Beş (5)"] },
  55:  { q: "Yüksek Mahkeme yargıçları ne kadar süre görev yapar?",
         cue: "ne kadar süre",
         a: ["Ömür boyu", "Ömür boyu atama", "Emekliliğe kadar"] },
  56:  { q: "Yüksek Mahkeme yargıçları ömür boyu görev yapar. Neden?",
         cue: "ömür boyu",
         a: ["(Siyasetten) bağımsız olmak için", "Dış (siyasi) etkiyi sınırlamak için"] },
  57:  { q: "Şu anda ABD Yüksek Mahkeme Başkanı (Chief Justice) kimdir?",
         cue: "Chief Justice",
         a: null },
  58:  { q: "Yalnızca federal hükümete ait bir yetkiyi söyleyin.",
         cue: "Yalnızca federal",
         a: ["Kâğıt para basmak", "Madeni para basmak", "Savaş ilan etmek", "Ordu kurmak", "Antlaşmalar yapmak", "Dış politikayı belirlemek"] },
  59:  { q: "Yalnızca eyaletlere ait bir yetkiyi söyleyin.",
         cue: "Yalnızca eyaletlere",
         a: ["Okul ve eğitim sağlamak", "Koruma (polis) sağlamak", "Güvenlik (itfaiye) sağlamak", "Ehliyet vermek", "İmar ve arazi kullanımını onaylamak"] },
  60:  { q: "10. Anayasa Değişikliği'nin amacı nedir?",
         cue: "10. Anayasa Değişikliği",
         a: ["Federal hükümete verilmeyen yetkilerin eyaletlere veya halka ait olduğunu belirtir."] },
  61:  { q: "Şu anda eyaletinizin valisi kimdir?",
         cue: "valisi",
         a: null },
  62:  { q: "Eyaletinizin başkenti neresidir?",
         cue: "Eyaletinizin başkenti",
         a: null },
  63:  { q: "ABD Anayasası'nda kimlerin oy kullanabileceğine dair dört değişiklik vardır. Birini açıklayın.",
         cue: "dört değişiklik",
         a: ["On sekiz (18) yaş ve üzeri vatandaşlar (oy kullanabilir).", "Oy vermek için (seçim vergisi) ödemek zorunda değilsiniz.", "Her vatandaş oy kullanabilir. (Kadınlar da erkekler de oy kullanabilir.)", "Her ırktan erkek vatandaş (oy kullanabilir)."] },
  64:  { q: "ABD'de federal seçimlerde kim oy kullanabilir, federal göreve aday olabilir ve jüride görev yapabilir?",
         cue: "jüride görev",
         a: ["Vatandaşlar", "Amerika Birleşik Devletleri vatandaşları", "ABD vatandaşları"] },
  65:  { q: "ABD'de yaşayan herkesin sahip olduğu üç hakkı söyleyin.",
         cue: "üç hakkı",
         a: ["İfade özgürlüğü", "Konuşma özgürlüğü", "Toplanma özgürlüğü", "Hükümete dilekçe verme özgürlüğü", "Din özgürlüğü", "Silah taşıma hakkı"] },
  66:  { q: "Bağlılık Andı'nı (Pledge of Allegiance) söylerken neye bağlılık gösteririz?",
         cue: "Pledge of Allegiance",
         a: ["Amerika Birleşik Devletleri'ne", "Bayrağa"] },
  67:  { q: "Yeni vatandaşların Bağlılık Yemini'nde verdiği iki sözü söyleyin.",
         cue: "iki sözü",
         a: ["Diğer ülkelere bağlılıktan vazgeçmek", "(ABD) Anayasası'nı savunmak", "ABD yasalarına uymak", "(Gerekirse) askerlik yapmak", "(Gerekirse) ulusa hizmet etmek (yardım etmek, önemli işler yapmak)", "Amerika Birleşik Devletleri'ne sadık olmak"] },
  68:  { q: "İnsanlar nasıl Amerika Birleşik Devletleri vatandaşı olabilir?",
         cue: "vatandaşı olabilir",
         a: ["14. Anayasa Değişikliği'nin koşulları altında ABD'de doğarak", "Naturalizasyon (vatandaşlığa geçiş) yoluyla", "(Kongre'nin belirlediği koşullarda) türetilmiş vatandaşlıkla"] },
  69:  { q: "ABD'de sivil katılıma iki örnek verin.",
         cue: "sivil katılıma",
         a: ["Oy vermek", "Aday olmak", "Bir siyasi partiye katılmak", "Bir kampanyaya yardım etmek", "Bir sivil gruba katılmak", "Bir topluluk grubuna katılmak", "Seçilmiş bir yetkiliye (bir konuda) görüşünü iletmek", "Seçilmiş yetkililerle iletişim kurmak", "Bir konuyu veya politikayı desteklemek ya da ona karşı çıkmak", "Bir gazeteye yazmak"] },
  70:  { q: "Amerikalıların ülkelerine hizmet etmesinin bir yolunu söyleyin.",
         cue: "ülkelerine hizmet",
         a: ["Oy vermek", "Vergi ödemek", "Yasalara uymak", "Askerlik yapmak", "Aday olmak", "Yerel, eyalet veya federal hükümette çalışmak"] },
  71:  { q: "Federal vergileri ödemek neden önemlidir?",
         cue: "Federal vergileri",
         a: ["Yasa gereğidir", "Herkes federal hükümeti finanse etmek için öder", "(ABD) Anayasası gereğidir (16. Değişiklik)", "Yurttaşlık görevidir"] },
  72:  { q: "18-25 yaş arasındaki tüm erkeklerin Selective Service'e (askerlik kaydı) kaydolması önemlidir. Bir neden söyleyin.",
         cue: "Selective Service",
         a: ["Yasa gereğidir", "Yurttaşlık görevidir", "Gerekirse askere almayı adil kılar"] },
  73:  { q: "Kolonistler Amerika'ya birçok nedenle geldi. Birini söyleyin.",
         cue: "Kolonistler",
         a: ["Özgürlük", "Siyasi özgürlük", "Din özgürlüğü", "Ekonomik fırsat", "Zulümden kaçış"] },
  74:  { q: "Avrupalılar gelmeden önce Amerika'da kim yaşıyordu?",
         cue: "Avrupalılar gelmeden önce",
         a: ["Amerikan Yerlileri", "Yerli Amerikalılar (Native Americans)"] },
  75:  { q: "Hangi insan grubu köle olarak alınıp satıldı?",
         cue: "köle olarak",
         a: ["Afrikalılar", "Afrika'dan gelen insanlar"] },
  76:  { q: "Amerikalılar İngiltere'den bağımsızlığı kazanmak için hangi savaşı verdi?",
         cue: "bağımsızlığı kazanmak",
         a: ["Amerikan Devrimi", "(Amerikan) Devrim Savaşı", "(Amerikan) Bağımsızlık Savaşı"] },
  77:  { q: "Amerikalıların İngiltere'den bağımsızlık ilan etmesinin bir nedenini söyleyin.",
         cue: "bağımsızlık ilan etmesinin",
         a: ["Yüksek vergiler", "Temsilsiz vergilendirme", "İngiliz askerlerinin Amerikalıların evlerinde kalması (konaklama zorunluluğu)", "Öz yönetimlerinin olmaması", "Boston Katliamı", "Boston Çay Partisi (Çay Yasası)", "Damga Yasası", "Şeker Yasası", "Townshend Yasaları", "Katlanılmaz (Zorlayıcı) Yasalar"] },
  78:  { q: "Bağımsızlık Bildirgesi'ni kim yazdı?",
         cue: "Bağımsızlık Bildirgesi'ni",
         a: null },
  79:  { q: "Bağımsızlık Bildirgesi ne zaman kabul edildi?",
         cue: "ne zaman kabul edildi",
         a: ["4 Temmuz 1776"] },
  80:  { q: "Amerikan Devrimi'nde birçok önemli olay yaşandı. Birini söyleyin.",
         cue: "Amerikan Devrimi'nde",
         a: ["Bunker Hill (Savaşı)", "Bağımsızlık Bildirgesi", "Washington'ın Delaware Nehri'ni Geçişi (Trenton Savaşı)", "Saratoga (Savaşı)", "Valley Forge (Kampı)", "Yorktown (Savaşı) (İngilizlerin Yorktown'da teslim olması)"] },
  81:  { q: "13 kurucu eyalet vardı. Beşini sayın.",
         cue: "13 kurucu eyalet",
         a: null },
  82:  { q: "1787'de hangi kurucu belge yazıldı?",
         cue: "1787",
         a: ["(ABD) Anayasası"] },
  83:  { q: "Federalist Yazıları ABD Anayasası'nın kabulünü destekledi. Yazarlarından birini söyleyin.",
         cue: "Yazarlarından birini",
         a: null },
  84:  { q: "Federalist Yazıları neden önemliydi?",
         cue: "Federalist Yazıları",
         a: ["İnsanların (ABD) Anayasası'nı anlamasına yardımcı oldular.", "(ABD) Anayasası'nın kabul edilmesini desteklediler."] },
  85:  { q: "Benjamin Franklin birçok şeyle ünlüdür. Birini söyleyin.",
         cue: "Benjamin Franklin",
         a: ["İlk ücretsiz halk kütüphanelerini kurdu", "ABD'nin ilk Posta Genel Müdürü", "Bağımsızlık Bildirgesi'nin yazımına yardım etti", "Mucit", "ABD diplomatı"] },
  86:  { q: "George Washington birçok şeyle ünlüdür. Birini söyleyin.",
         cue: "George Washington",
         a: ["\"Ülkemizin Babası\"", "ABD'nin ilk başkanı", "Kıta Ordusu'nun generali", "Anayasa Konvansiyonu'nun başkanı"] },
  87:  { q: "Thomas Jefferson birçok şeyle ünlüdür. Birini söyleyin.",
         cue: "Thomas Jefferson",
         a: ["Bağımsızlık Bildirgesi'nin yazarı", "ABD'nin üçüncü başkanı", "ABD'nin yüzölçümünü ikiye katladı (Louisiana Alımı)", "İlk Dışişleri Bakanı", "Virginia Üniversitesi'ni kurdu", "Virginia Din Özgürlüğü Tüzüğü'nün yazarı"] },
  88:  { q: "James Madison birçok şeyle ünlüdür. Birini söyleyin.",
         cue: "James Madison",
         a: ["\"Anayasa'nın Babası\"", "ABD'nin dördüncü başkanı", "1812 Savaşı sırasında başkan", "Federalist Yazıları'nın yazarlarından biri"] },
  89:  { q: "Alexander Hamilton birçok şeyle ünlüdür. Birini söyleyin.",
         cue: "Alexander Hamilton",
         a: ["İlk Hazine Bakanı", "Federalist Yazıları'nın yazarlarından biri", "ABD'nin İlk Bankası'nın kurulmasına yardım etti", "General George Washington'ın yaveri", "Kıta Kongresi üyesi"] },
  90:  { q: "ABD 1803'te Fransa'dan hangi bölgeyi satın aldı?",
         cue: "1803'te Fransa'dan",
         a: ["Louisiana Bölgesi", "Louisiana"] },
  91:  { q: "ABD'nin 1800'lerde katıldığı bir savaşı söyleyin.",
         cue: "1800'lerde",
         a: ["1812 Savaşı", "Meksika-Amerika Savaşı", "İç Savaş", "İspanya-Amerika Savaşı"] },
  92:  { q: "Kuzey ile Güney arasındaki ABD savaşının adını söyleyin.",
         cue: "Kuzey ile Güney",
         a: ["İç Savaş (Civil War)"] },
  93:  { q: "İç Savaş'ta birçok önemli olay yaşandı. Birini söyleyin.",
         cue: "İç Savaş'ta",
         a: ["Fort Sumter (Savaşı)", "Özgürlük Bildirisi (Emancipation Proclamation)", "Vicksburg (Savaşı)", "Gettysburg (Savaşı)", "Sherman'ın Yürüyüşü", "(Appomattox'ta) Teslim", "Antietam/Sharpsburg (Savaşı)", "Lincoln suikasta uğradı."] },
  94:  { q: "Abraham Lincoln birçok şeyle ünlüdür. Birini söyleyin.",
         cue: "Abraham Lincoln",
         a: ["Köleleri özgürleştirdi (Özgürlük Bildirisi)", "Birliği kurtardı (korudu)", "İç Savaş sırasında ABD'yi yönetti", "ABD'nin 16. başkanı", "Gettysburg Konuşması'nı yaptı"] },
  95:  { q: "Özgürlük Bildirisi (Emancipation Proclamation) ne yaptı?",
         cue: "Emancipation Proclamation",
         a: ["Köleleri özgürleştirdi", "Konfederasyon'daki köleleri özgürleştirdi", "Konfederasyon eyaletlerindeki köleleri özgürleştirdi", "Güney eyaletlerinin çoğundaki köleleri özgürleştirdi"] },
  96:  { q: "Hangi ABD savaşı köleliği bitirdi?",
         cue: "köleliği bitirdi",
         a: ["İç Savaş (Civil War)"] },
  97:  { q: "Hangi anayasa değişikliği, ABD'de doğan veya naturalize olan ve ABD yargı yetkisine tabi herkesin ABD vatandaşı olduğunu söyler?",
         cue: "doğan veya naturalize",
         a: ["14. Anayasa Değişikliği"] },
  98:  { q: "Tüm erkekler oy hakkını ne zaman aldı?",
         cue: "Tüm erkekler",
         a: ["İç Savaş'tan sonra", "Yeniden Yapılanma (Reconstruction) döneminde", "15. Anayasa Değişikliği (ile)", "1870"] },
  99:  { q: "1800'lerdeki kadın hakları hareketinin bir liderini söyleyin.",
         cue: "kadın hakları hareketinin",
         a: null },
  100: { q: "ABD'nin 1900'lerde katıldığı bir savaşı söyleyin.",
         cue: "1900'lerde",
         a: ["Birinci Dünya Savaşı", "İkinci Dünya Savaşı", "Kore Savaşı", "Vietnam Savaşı", "(Basra) Körfez Savaşı"] },
  101: { q: "ABD Birinci Dünya Savaşı'na neden girdi?",
         cue: "Birinci Dünya Savaşı",
         a: ["Almanya ABD (sivil) gemilerine saldırdığı için", "İtilaf Devletleri'ni (İngiltere, Fransa, İtalya ve Rusya) desteklemek için", "İttifak Devletleri'ne (Almanya, Avusturya-Macaristan, Osmanlı İmparatorluğu ve Bulgaristan) karşı koymak için"] },
  102: { q: "Tüm kadınlar oy hakkını ne zaman aldı?",
         cue: "Tüm kadınlar",
         a: ["1920", "Birinci Dünya Savaşı'ndan sonra", "19. Anayasa Değişikliği (ile)"] },
  103: { q: "Büyük Buhran neydi?",
         cue: "Büyük Buhran",
         a: ["Modern tarihin en uzun ekonomik durgunluğu"] },
  104: { q: "Büyük Buhran ne zaman başladı?",
         cue: "ne zaman başladı",
         a: ["Büyük Çöküş (1929)", "1929 borsa çöküşü"] },
  105: { q: "Büyük Buhran ve İkinci Dünya Savaşı sırasında başkan kimdi?",
         cue: "Buhran ve İkinci Dünya Savaşı",
         a: ["(Franklin) Roosevelt"] },
  106: { q: "ABD İkinci Dünya Savaşı'na neden girdi?",
         cue: "İkinci Dünya Savaşı'na neden girdi",
         a: ["Pearl Harbor'ın (bombalanması)", "Japonların Pearl Harbor'a saldırması", "Müttefik Devletleri (İngiltere, Fransa ve Rusya) desteklemek için", "Mihver Devletleri'ne (Almanya, İtalya ve Japonya) karşı koymak için"] },
  107: { q: "Dwight Eisenhower birçok şeyle ünlüdür. Birini söyleyin.",
         cue: "Dwight Eisenhower",
         a: ["İkinci Dünya Savaşı'nda general", "Kore Savaşı'nın sonunda (sırasında) başkan", "ABD'nin 34. başkanı", "1956 Federal Otoyol Yasası'nı imzaladı (Eyaletlerarası Otoyol Sistemi'ni kurdu)"] },
  108: { q: "Soğuk Savaş sırasında ABD'nin ana rakibi kimdi?",
         cue: "ana rakibi",
         a: ["Sovyetler Birliği", "SSCB", "Rusya"] },
  109: { q: "Soğuk Savaş sırasında ABD'nin bir ana endişesi neydi?",
         cue: "ana endişesi",
         a: ["Komünizm", "Nükleer savaş"] },
  110: { q: "ABD Kore Savaşı'na neden girdi?",
         cue: "Kore Savaşı",
         a: ["Komünizmin yayılmasını durdurmak için"] },
  111: { q: "ABD Vietnam Savaşı'na neden girdi?",
         cue: "Vietnam Savaşı",
         a: ["Komünizmin yayılmasını durdurmak için"] },
  112: { q: "Sivil haklar hareketi ne yaptı?",
         cue: "Sivil haklar hareketi",
         a: ["Irk ayrımcılığını bitirmek için mücadele etti"] },
  113: { q: "Martin Luther King, Jr. birçok şeyle ünlüdür. Birini söyleyin.",
         cue: "Martin Luther King",
         a: ["Sivil haklar için mücadele etti", "Tüm Amerikalılar için eşitlik için çalıştı", "İnsanların \"derilerinin rengiyle değil, karakterlerinin içeriğiyle\" değerlendirilmesini sağlamak için çalıştı"] },
  114: { q: "ABD Basra Körfezi Savaşı'na neden girdi?",
         cue: "Basra Körfezi",
         a: ["Irak ordusunu Kuveyt'ten çıkarmak için"] },
  115: { q: "11 Eylül 2001'de ABD'de hangi büyük olay yaşandı?",
         cue: "11 Eylül 2001",
         a: ["Teröristler Amerika Birleşik Devletleri'ne saldırdı", "Teröristler iki uçağı kaçırıp New York'taki Dünya Ticaret Merkezi'ne çarptılar", "Teröristler bir uçağı kaçırıp Virginia, Arlington'daki Pentagon'a çarptılar", "Teröristler aslen Washington D.C.'yi hedefleyen bir uçağı kaçırdı; uçak Pennsylvania'da bir tarlaya düştü"] },
  116: { q: "11 Eylül 2001 saldırılarından sonraki bir ABD askeri çatışmasını söyleyin.",
         cue: "saldırılarından sonraki",
         a: ["(Küresel) Terörle Savaş", "Afganistan Savaşı", "Irak Savaşı"] },
  117: { q: "ABD'deki bir Amerikan Yerli kabilesinin adını söyleyin.",
         cue: "Yerli kabilesinin",
         a: null },
  118: { q: "Bir Amerikan buluşu örneği verin.",
         cue: "Amerikan buluşu",
         a: ["Ampul", "Otomobil (arabalar, içten yanmalı motor)", "Gökdelenler", "Uçak", "Montaj hattı", "Ay'a iniş", "Entegre devre (IC)"] },
  119: { q: "Amerika Birleşik Devletleri'nin başkenti neresidir?",
         cue: "Devletleri'nin başkenti",
         a: ["Washington, D.C."] },
  120: { q: "Özgürlük Heykeli nerededir?",
         cue: "Özgürlük Heykeli",
         a: ["New York (Limanı)", "Liberty Adası"] },
  121: { q: "Bayrakta neden 13 çizgi vardır?",
         cue: "13 çizgi",
         a: ["(Çünkü) 13 kurucu koloni (vardı)", "(Çünkü çizgiler) kurucu kolonileri temsil eder"] },
  122: { q: "Bayrakta neden 50 yıldız vardır?",
         cue: "50 yıldız",
         a: ["(Çünkü) her eyalet için bir yıldız (vardır)", "(Çünkü) her yıldız bir eyaleti temsil eder", "(Çünkü) 50 eyalet (vardır)"] },
  123: { q: "Milli marşın adı nedir?",
         cue: "Milli marşın",
         a: null },
  124: { q: "Ulusun ilk mottosu \"E Pluribus Unum\"du. Bu ne anlama gelir?",
         cue: "E Pluribus Unum",
         a: ["Çokluktan birlik", "Hepimiz bir oluruz"] },
  125: { q: "Independence Day (Bağımsızlık Günü) nedir?",
         cue: "Independence Day",
         a: ["ABD'nin (İngiltere'den) bağımsızlığını kutlayan bir bayram", "Ülkenin doğum günü"] },
  126: { q: "Üç ulusal ABD bayramı sayın.",
         cue: "Üç ulusal",
         a: ["Yılbaşı", "Martin Luther King, Jr. Günü", "Başkanlar Günü (Washington'ın Doğum Günü)", "Anma Günü (Memorial Day)", "Juneteenth", "Bağımsızlık Günü", "İşçi Bayramı (Labor Day)", "Kolomb Günü", "Gaziler Günü (Veterans Day)", "Şükran Günü (Thanksgiving)", "Noel"] },
  127: { q: "Memorial Day (Anma Günü) nedir?",
         cue: "Memorial Day",
         a: ["Askerlik görevinde ölen askerleri onurlandıran bir bayram"] },
  128: { q: "Veterans Day (Gaziler Günü) nedir?",
         cue: "Veterans Day",
         a: ["(ABD) ordusundaki insanları onurlandıran bir bayram", "(ABD ordusunda) görev yapmış insanları onurlandıran bir bayram"] }
};
